from tkinter import *
import tkinter.messagebox as messagebox
import random,time,sqlite3
import datetime 
counter=1
conn=sqlite3.connect('database.db')
c=conn.cursor()
root=Tk()
root.title("Ice Cream Billing System")
root.geometry('1300x750+0+0')
##rimg=PhotoImage(file="reset.png")
##reimg=PhotoImage(file="bill.png")
##timg=PhotoImage(file="cal.png")
##qimg=PhotoImage(file="exit.png")
##himg=PhotoImage(file="home.png")
##simg=PhotoImage(file="sav.png")
seimg=PhotoImage(file='search.png')
def bills():
   root.withdraw()
   billing=Toplevel()
   billing.title("Ice Cream Billing system")
   billing.geometry("1300x750+0+0")
   tf=Frame(billing,width=900,height=75,relief='sunken',bd=10)
   tf.place(x=0,y=0)
   lf=Frame(billing,width=900,height=625,relief="ridge",bd=10)
   lf.place(x=0,y=100)
   lf1a=Frame(lf,width=450,height=500,relief="ridge",bd=10)
   lf1a.place(x=0,y=10)
   lf1b=Frame(lf,width=450,height=500,relief="ridge",bd=10)
   lf1b.place(x=425,y=10)
   lf2a=Frame(lf,width=450,height=125,relief="ridge",bd=10)
   lf2a.place(x=0,y=425)
   lf2b=Frame(lf,width=450,height=125,relief="ridge",bd=10)
   lf2b.place(x=425,y=425)
   rf=Frame(billing,width=400,height=750,relief="ridge",bd=10)
   rf.place(x=900,y=0)
   rf1=Frame(rf,width=400,height=75,relief="ridge",bd=10)
   rf1.place(x=0,y=0)
   rf2=Frame(rf,width=400,height=525,relief="ridge",bd=10)
   rf2.place(x=0,y=50)
   rf3=Frame(rf,width=400,height=250,relief="ridge",bd=10)
   rf3.place(x=0,y=520)
   def create_table():
       c.execute("CREATE TABLE IF NOT EXISTS data2(bill_no TEXT,chocobar INTEGER,strawberry INTEGER,vanilla INTEGER,butterscotch INTEGER,kulfi INTEGER,ice_cream_cake INTEGER,mint_ice INTEGER,cone_ice INTEGER,cup_ice INTEGER,mango_bar INTEGER,sub_total INTEGER,service_charge REAL,tax REAL,amount REAL)")
       conn.commit()
   def insert(bno,chocobar,strawberry,vanilla,butterscotch,kulfi,icecake,mintice,coneice,cupice,mangobar,subtotal,sc,tax,cost):
       c.execute("INSERT INTO data2(bill_no ,chocobar,strawberry,vanilla,butterscotch,kulfi,ice_cream_cake,mint_ice,cup_ice,cone_ice,mango_bar,sub_total,service_charge,tax,amount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",(bno,chocobar,strawberry,vanilla,butterscotch,kulfi,icecake,mintice,coneice,cupice,mangobar,subtotal,sc,tax,cost))
       conn.commit()
   def reciept():
       global counter
       if counter :
           txt.configure(state='normal')
           bno=random.randrange(11111,99999)
           txt.insert("1.0","\t A-Z IceCream \t \n \n ")
           txt.insert(END,"--------------------------------------------- \n")
           txt.insert(END,"Bill no. \t \t" +str(bno)+"\n")
           txt.insert(END,"--------------------------------------------- \n")
           txt.insert(END,"Item \t\tQty\tRate\n")
           txt.insert(END,"--------------------------------------------- \n")
           txt.insert(END,"Chocobar \t \t" +str(var1.get())+"\t10 Rs/-\n \n")
           txt.insert(END,"Strawberry \t \t" +str(var2.get())+"\t20 Rs/- \n  \n")
           txt.insert(END,"Vanilla \t \t" +str(var3.get())+"\t20 Rs/- \n \n")
           txt.insert(END,"Butterscotch\t \t" +str(var4.get())+" \t30 Rs/-\n \n")
           txt.insert(END,"Kulfi \t \t" +str(var5.get())+"\t15 Rs/-\n \n")
           txt.insert(END,"Ice cream cake \t \t" +str(var6.get()) +"\t75 Rs/-\n \n")
           txt.insert(END,"Mint Ice cream \t \t" +str(var7.get())+"\t50 Rs/-\n \n")
           txt.insert(END,"Cone ice \t \t" +str(var8.get())+"\t40 Rs/-\n \n")
           txt.insert(END,"Cup ice \t \t" +str(var9.get())+"\t30 Rs/-\n \n")
           txt.insert(END,"Mango bar \t \t" +str(var10.get())+"\t35 Rs/-\n \n")
           txt.insert(END,"------------------------------------ \n \n")        
           txt.insert(END,"Sub total \t \t" +str(var11.get())+"\n \n")
           txt.insert(END,"Service charge \t \t" +str(var12.get())+"\n \n")
           txt.insert(END,"Tax \t \t" +str(var13.get())+"\n \n")
           txt.insert(END,"Total cost \t \t" +str(var14.get())+"\n \n")
           txt.configure(state='disabled')
           counter=0
       else:
           messagebox.showinfo("Warning",'Reset First')
   def save():
        bno=random.randrange(11111,99999)
        y=messagebox.askyesno('Confirm','Do you want to save')
        if y>0:
           create_table()
           chocobar=var1.get()
           strawberry=var2.get()
           vanilla=var3.get()
           butterscotch=var4.get()
           kulfi=var5.get()
           icecake=var6.get()
           mintice=var7.get()
           coneice=var8.get()
           cupice=var9.get()
           mangobar=var10.get()
           subtotal=var11.get()
           sc=var12.get()
           tax=var13.get()
           cost=var14.get()
           insert(bno,chocobar,strawberry,vanilla,butterscotch,kulfi,icecake,mintice,coneice,cupice,mangobar,subtotal,sc,tax,cost)
           messagebox.showinfo('Success','Successfully Saved')
        else:
           pass
   def goback():
      root.deiconify()
      billing.withdraw()
   def total():
       e11.configure(state='normal')
       e11.configure(state='normal')
       e11.configure(state='normal')
       e11.configure(state='normal')
       subtot=var1.get()*10+var2.get()*20+var3.get()*20+var4.get()*30+var5.get()*15+var6.get()*75+var7.get()*50+var8.get()*40+var9.get()*30+var10.get()*35
       var11.set(subtot)
       tax=var1.get()*10*0.05+var2.get()*20*0.05+var3.get()*2*0.050+var4.get()*3*0.050+var5.get()*15*0.05+var6.get()*75*0.05+var7.get()*50*0.05+var8.get()*40*0.05+var9.get()*30*0.05+var10.get()*35*0.05
       var13.set(tax)
       sc=round(subtot*0.06,2)
       var12.set(sc)
       tot=subtot+tax+sc
       var14.set(tot)
       e11.configure(state='disabled')
       e11.configure(state='disabled')
       e11.configure(state='disabled')
       e11.configure(state='disabled')
   def quit():
       e=messagebox.askyesno("Billing System","Do you want to exit")
       if e>0:
           billing.destroy()
   def reset():
       global counter
       counter=1
       txt.configure(state='normal')
       var1.set("0")
       var2.set("0")
       var3.set("0")
       var4.set("0")
       var5.set("0")
       var6.set("0")
       var7.set("0")
       var8.set("0")
       var9.set("0")
       var10.set("0")
       var11.set("0.0")
       var12.set("0.0")
       var13.set("0.0")
       var14.set("0.0")
       txt.delete("1.0",END)
       txt.configure(state='disabled')
   title=Label(tf,font=("georgia",30,"bold"),fg="blue",text="                    A-Z   ICE-CREAMS                           ")
   title.pack(side=LEFT)
   typ1=Label(lf1a,text="Type",font=('georgia',20,'bold'),fg='blue')
   typ1.grid(row=0,column=0,padx=10,pady=10,sticky=W)
   qty1=Label(lf1a,text="Qty",font=('georgia',20,'bold'),fg='blue')
   qty1.grid(row=0,column=1,padx=10,pady=10,sticky=W)
   rate1=Label(lf1a,text="Rate",font=('georgia',20,'bold'),fg='blue')
   rate1.grid(row=0,column=2,padx=10,pady=10,sticky=W)
   l1=Label(lf1a,text="Chocobar",font=('arial',20,'bold'),fg='blue4')
   l1.grid(row=1,column=0,padx=10,pady=10,sticky=W)
   l2=Label(lf1a,text="Strawberry",font=('arial',20,'bold'),fg='blue4')
   l2.grid(row=2,column=0,padx=10,pady=10,sticky=W)
   l3=Label(lf1a,text="Vanilla",font=('arial',20,'bold'),fg="blue4")
   l3.grid(row=3,column=0,padx=10,pady=10,sticky=W)
   l4=Label(lf1a,text="Butterscotch",font=('arial',20,'bold'),fg='blue4')
   l4.grid(row=4,column=0,padx=10,pady=10,sticky=W)
   l5=Label(lf1a,text="Kulfi",font=('arial',20,'bold'),fg='blue4')
   l5.grid(row=5,column=0,padx=10,pady=10,sticky=W)
   typ2=Label(lf1b,text="Type",font=('georgia',20,'bold'),fg='blue')
   typ2.grid(row=0,column=0,padx=10,pady=10,sticky=W)
   qty2=Label(lf1b,text="Qty",font=('georgia',20,'bold'),fg='blue')
   qty2.grid(row=0,column=1,padx=10,pady=10,sticky=W)
   rate2=Label(lf1b,text="Rate",font=('georgia',20,'bold'),fg='blue')
   rate2.grid(row=0,column=2,padx=10,pady=10,sticky=W)
   l6=Label(lf1b,text="Icecream cake",font=('arial',20,'bold'),fg='blue4')
   l6.grid(row=1,column=0,padx=10,pady=10,sticky=W)
   l7=Label(lf1b,text="Mint Ice cream",font=('arial',20,'bold'),fg='blue4')
   l7.grid(row=2,column=0,padx=10,pady=10,sticky=W)
   l8=Label(lf1b,text="Cone Ice",font=('arial',20,'bold'),fg='blue4')
   l8.grid(row=3,column=0,padx=10,pady=10,sticky=W)
   l9=Label(lf1b,text="Cup Ice",font=('arial',20,'bold'),fg='blue4')
   l9.grid(row=4,column=0,padx=10,pady=10,sticky=W)
   l10=Label(lf1b,text="Mango bar",font=('arial',20,'bold'),fg='blue4')
   l10.grid(row=5,column=0,padx=10,pady=10,sticky=W)
   l11=Label(lf2a,text="Sub total",font=('arial',20,'bold'),fg='blue4')
   l11.grid(row=0,column=0,padx=10,pady=10,sticky=W)
   l13=Label(lf2a,text="Service charge",font=('arial',20,'bold'),fg='blue4')
   l13.grid(row=1,column=0,padx=10,pady=10,sticky=W)
   l12=Label(lf2b,text="Tax Charge",font=('arial',20,'bold'),fg='blue4')
   l12.grid(row=0,column=0,padx=10,pady=10,sticky=W)
   l14=Label(lf2b,text="Total Cost",font=('arial',20,'bold'),fg='blue4')
   l14.grid(row=1,column=0,padx=10,pady=10,sticky=W)
   l15=Label(lf2a,text="Rs/-",font=('arial',20,'bold'),fg='red2')
   l15.grid(row=0,column=2,pady=10,sticky=W)
   l16=Label(lf2a,text="Rs/-",font=('arial',20,'bold'),fg='red2')
   l16.grid(row=1,column=2,pady=10,sticky=W)
   l17=Label(lf2b,text="Rs/-",font=('arial',20,'bold'),fg='red2')
   l17.grid(row=0,column=2,pady=10,sticky=W)
   l18=Label(lf2b,text="Rs/-",font=('arial',20,'bold'),fg='red2')
   l18.grid(row=1,column=2,pady=10,sticky=W)
   l19=Label(rf1,text="Receipt",font=('arial',15,'bold'),fg='blue')
   l19.grid(row=0,column=0,padx=10,sticky=W)
   r1=Label(lf1a,text="10 Rs/-",font=('arial',20,'bold'),fg='red2')
   r1.grid(row=1,column=2,padx=10,pady=10,sticky=W)
   r2=Label(lf1a,text="20 Rs/-",font=('arial',20,'bold'),fg='red2')
   r2.grid(row=2,column=2,padx=10,pady=10,sticky=W)
   r3=Label(lf1a,text="20 Rs/-",font=('arial',20,'bold'),fg='red2')
   r3.grid(row=3,column=2,padx=10,pady=10,sticky=W)
   r4=Label(lf1a,text="30 Rs/-",font=('arial',20,'bold'),fg='red2')
   r4.grid(row=4,column=2,padx=10,pady=10,sticky=W)
   r5=Label(lf1a,text="15 Rs/-",font=('arial',20,'bold'),fg='red2')
   r5.grid(row=5,column=2,padx=10,pady=10,sticky=W)
   r6=Label(lf1b,text="75 Rs/-",font=('arial',20,'bold'),fg='red2')
   r6.grid(row=1,column=2,padx=10,pady=10,sticky=W)
   r7=Label(lf1b,text="50 Rs/-",font=('arial',20,'bold'),fg='red2')
   r7.grid(row=2,column=2,padx=10,pady=10,sticky=W)
   r8=Label(lf1b,text="40 Rs/-",font=('arial',20,'bold'),fg='red2')
   r8.grid(row=3,column=2,padx=10,pady=10,sticky=W)
   r9=Label(lf1b,text="30 Rs/-",font=('arial',20,'bold'),fg='red2')
   r9.grid(row=4,column=2,padx=10,pady=10,sticky=W)
   r10=Label(lf1b,text="35 Rs/-",font=('arial',20,'bold'),fg='red2')
   r10.grid(row=5,column=2,padx=10,pady=10,sticky=W)
   var1=IntVar()
   var2=IntVar()
   var3=IntVar()
   var4=IntVar()
   var5=IntVar()
   var6=IntVar()
   var7=IntVar()
   var8=IntVar()
   var9=IntVar()
   var10=IntVar()
   var11=DoubleVar()
   var12=DoubleVar()
   var13=DoubleVar()
   var14=DoubleVar()
   var15=IntVar()
   #===================Entries==========================
   e1=Entry(lf1a,font=('arial',20,'bold'),fg="black",width=5,bg='powder blue',textvariable=var1)
   e1.grid(row=1,column=1,sticky=E,padx=10,pady=10)
   e2=Entry(lf1a,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var2)
   e2.grid(row=2,column=1,sticky=E,padx=10,pady=10)
   e3=Entry(lf1a,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var3)
   e3.grid(row=3,column=1,sticky=E,padx=10,pady=10)
   e4=Entry(lf1a,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var4)
   e4.grid(row=4,column=1,sticky=E,padx=10,pady=10)
   e5=Entry(lf1a,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var5)
   e5.grid(row=5,column=1,sticky=E,padx=10,pady=10)
   e6=Entry(lf1b,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var6)
   e6.grid(row=1,column=1,sticky=E,padx=10,pady=10)
   e7=Entry(lf1b,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var7)
   e7.grid(row=2,column=1,sticky=E,padx=10,pady=10)
   e8=Entry(lf1b,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var8)
   e8.grid(row=3,column=1,sticky=E,padx=10,pady=10)
   e9=Entry(lf1b,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var9)
   e9.grid(row=4,column=1,sticky=E,padx=10,pady=10)
   e10=Entry(lf1b,font=('arial',20,'bold'),fg="black",bg='powder blue',width=5,textvariable=var10)
   e10.grid(row=5,column=1,sticky=E,padx=10,pady=10)
   e11=Entry(lf2a,font=('arial',20,'bold'),fg="black",bg='powder blue',width=7,textvariable=var11)
   e11.grid(row=0,column=1,sticky=E,padx=10,pady=10)
   e11.configure(state='disabled')
   e12=Entry(lf2a,font=('arial',20,'bold'),fg="black",bg='powder blue',width=7,textvariable=var12)
   e12.grid(row=1,column=1,sticky=E,padx=10,pady=10)
   e12.configure(state='disabled')
   e13=Entry(lf2b,font=('arial',20,'bold'),fg="black",bg='powder blue',width=7,textvariable=var13)
   e13.grid(row=0,column=1,sticky=E,padx=10,pady=10)
   e13.configure(state='disabled')
   e14=Entry(lf2b,font=('arial',20,'bold'),fg="black",bg='powder blue',width=7,textvariable=var14)
   e14.grid(row=1,column=1,sticky=E,padx=10,pady=10)
   e14.configure(state='disabled')
   #=================Textbox=================
   txt=Text(rf2,font=('arial',12,'bold'),fg="blue4",width=35,height=23)
   txt.grid(row=0,column=0)
   s=Scrollbar(rf2)
   s.grid(row=0,column=1,ipady=15)
   s.config(command=txt.yview)
   txt.configure(state='disabled',yscrollcommand=s.set)
   #=================buttons====================
   b1=Button(rf3,text="Total",font=("georgia",15,'bold'),fg="black",bg='powder blue',relief='ridge',bd=8,command=total)
   b1.grid(row=0,column=1,padx=10,pady=10)
   b2=Button(rf3,text="Receipt",font=("georgia",15,'bold'),fg="black",bg='powder blue',relief='ridge',bd=8,command=reciept)
   b2.grid(row=0,column=2,padx=10,pady=10)
   b3=Button(rf3,text="Reset",font=("georgia",15,'bold'),fg="black",bg='powder blue',relief='ridge',bd=8,command=reset)
   b3.grid(row=0,column=3,padx=10,pady=10)
   b4=Button(rf3,text="Quit",font=("georgia",15,'bold'),fg="black",bg='powder blue',relief='ridge',bd=8,command=quit)
   b4.grid(row=1,column=3,padx=10,pady=5)
   b5=Button(rf3,text="Home",font=("georgia",15,'bold'),fg="black",bg='powder blue',relief='ridge',bd=8,command=goback)
   b5.grid(row=1,column=1,padx=10,pady=5)
   b6=Button(rf3,text="Save",font=("georgia",15,'bold'),fg="black",bg='powder blue',relief='ridge',bd=8,command=save)
   b6.grid(row=1,column=2,padx=10,pady=5)
   billing.mainloop()
def getinfo():
   root.withdraw()
   info=Toplevel()
   info.title("Ice Cream Billing System")
   info.geometry("1300x750+0+0")
   tf=Frame(info,width=700,height=60,relief='ridge',bd=10)
   tf.place(x=0,y=0)
   title=Label(tf,font=("georgia",30,"bold"),text="                        A-Z Ice-Creams                     ",fg="blue")
   title.pack()
   lf=Frame(info,width=800,height=600,relief='ridge',bd=10)
   lf.place(x=0,y=75)
   rf=Frame(info,width=495,height=670,relief='ridge',bd=10)
   rf.place(x=800,y=5)
   var15=IntVar()
   def back():
      info.withdraw()
      root.deiconify()
   def get():
       b=var15.get()
       txt.configure(state='normal')
       txt.delete('1.0',END)
       c.execute('SELECT * FROM data1 where bill_no='+str(b))
       d=c.fetchall()
       for i in d:
           txt.insert("1.0","\t A-Z  IceCream \t \n ")
           txt.insert(END,"--------------------------------------------- \n")
           txt.insert(END,"Bill no. \t \t \t" +str(i[0])+"\n \n")
           txt.insert(END,"Chocobar \t \t \t" +str(i[1])+"\n \n")
           txt.insert(END,"Strawberry \t \t \t" +str(i[2])+" \n  \n")
           txt.insert(END,"Vanilla \t \t \t" +str(i[3])+" \n \n")
           txt.insert(END,"Butterscotch \t \t \t" +str(i[4])+" \n \n")
           txt.insert(END,"Kulfi \t \t \t"+str(i[5])+"\n \n")
           txt.insert(END,"Ice cream cake  \t \t \t" +str(i[6]) +"\n \n")
           txt.insert(END,"Mint Ice cream \t \t \t" +str(i[7])+"\n \n")
           txt.insert(END,"Cone ice \t \t \t" +str(i[8])+"\n \n")
           txt.insert(END,"Cup ice \t \t \t" +str(i[9])+"\n \n")
           txt.insert(END,"Mango bar \t \t \t" +str(i[10])+"\n \n ")
           txt.insert(END,"-----------------------------------------------\n \n")
           txt.insert(END,"Sub total \t \t \t" +str(i[11])+"\n \n")
           txt.insert(END,"Service charge \t \t \t" +str(i[12])+"\n \n")
           txt.insert(END,"Tax \t \t \t" +str(i[13])+"\n \n")
           txt.insert(END,"Total cost \t \t \t" +str(i[14])+"\n \n")
           txt.configure(state='disabled')
   def delete():
         txt.configure(state='normal')
         txt.delete('1.0',END)
         var15.set("0")
         txt.configure(state='disabled')
   l1=Label(rf,text="Bill_no",font=('georgia',20,'bold'),relief='groove',bd=10,fg="blue")
   l1.place(x=5,y=5)
   e15=Entry(rf,font=('georgia',23,'bold'),fg="blue",relief='ridge',bd=10,width=7,textvariable=var15)
   e15.place(x=150,y=3)
   find=Button(lf,text="search",font=('georgia',15,'bold'),width=15,height=7,relief='ridge',bd=10,fg='blue',command=get)
   find.place(x=50,y=50)
   reset=Button(lf,text="Reset",font=('georgia',15,'bold'),width=15,height=7,relief='ridge',bd=10,fg='blue',command=delete)
   reset.place(x=500,y=50)
   home=Button(lf,text="Home",font=('georgia',15,'bold'),width=15,height=7,relief='ridge',bd=10,fg='blue',command=back)
   home.place(x=50,y=300)
   ex=Button(lf,text="Exit",font=('georgia',15,'bold'),width=15,height=7,relief='ridge',bd=10,fg='blue',command=exit)
   ex.place(x=500,y=300)
   txt=Text(rf,font=('georgia',12,'bold'),fg="blue",relief='ridge',bd=10,width=43,height=31)
   s=Scrollbar(rf,relief='ridge',bd=10)
   s.place(x=430,y=300)
   s.config(command=txt.yview)
   txt.configure(yscrollcommand=s.set,state='disabled')
   txt.place(x=10,y=60)
def exit():
   e=messagebox.askyesno('Exit','Do you want to exit')
   if e>0:
      root.destroy()
def billcolor1(event):
   billbtn['bg']="green2"
def billcolor2(event):
   billbtn['bg']="powder blue"
def reccolor1(event):
   recbtn['bg']="green2"
def reccolor2(event):
   recbtn['bg']="powder blue"
def excolor1(event):
   ex['bg']="powder blue"
def excolor2(event):
   ex['bg']='red' 
top=Frame(root,width=1300,height=60,relief='ridge',bd=10)
top.place(x=0,y=0)
title=Label(top,font=("georgia",35,),text="                               ICE CREAM BILLING SYSTEM                         ",fg="blue")
title.pack()
top1=Frame(root,width=1200,height=60,relief='sunken',bd=8)
top1.place(x=450,y=100)
que=Label(top1,text="Which System you want to load ?",font=('georgia',20),fg='blue')
que.pack()
billbtn=Button(root,bg='powder blue',font=('georgia',15),text="Billing System",relief='ridge',bd=10,width=40,height=10,command=bills)
billbtn.place(x=60,y=200)
billbtn.bind('<Enter>',billcolor1)
billbtn.bind('<Leave>',billcolor2)
recbtn=Button(root,bg='powder blue',font=('georgia',15),text="Retreival System",relief='ridge',bd=10,width=40,height=10,command=getinfo)
recbtn.place(x=740,y=200)
recbtn.bind('<Enter>',reccolor1)
recbtn.bind('<Leave>',reccolor2)
ex=Button(root,bg='powder blue',font=('georgia',15),text="Exit System",relief='ridge',bd=10,width=40,height=5,command=exit)
ex.place(x=400,y=500)
ex.bind('<Enter>',excolor2)
ex.bind('<Leave>',excolor1)
root.mainloop()
